### ISSUE TITLE
Missing Workplace contact matrix for North Carolina

### ISSUE THREAD

**Issue by ngozzi** [midas-network/covid19-smh-research_resources#1]
Hello,
I have noticed that prepandemic workplace [contact matrix](https://github.com/midas-network/covid19-smh-research_resources/tree/main/disparities/contact_matrix/north_carolina/contact_matrix) is not provided for North Carolina, will you provide this?
Thanks

**Comment by LucieContamin** [comment]
Hello @ngozzi ,

Thanks for your question, the contact matrix folder is still in progress. We plan to provide it. I will update the issue once it's done.

**Comment by LucieContamin** [comment]
Hello @ngozzi ,

The contact matrix folder has been updated to provide more information and resources, including a prepandemic workplace [contact matrix](https://github.com/midas-network/covid19-smh-research_resources/tree/main/disparities/contact_matrix/north_carolina/contact_matrix).
Please feel free to let me know if any questions.
